### ISSUE TITLE
Review / Audit All Documentation Pages

### ISSUE THREAD

**Issue by mattfwood** [cratebind/minerva-ui#96]
The documentation site (in `docs`) has some inconsistencies with how the components appear in Storybook.

We need someone to review each documentation page for:
- [ ] All example components render as expected (make sure styles match Storybook)
- [x] No errors are being rendered in examples (due to using outdated props)
- [x] Links within documentation are correct

**Comment by bekahlbaker** [comment]
<img width="459" alt="Screen Shot 2020-05-07 at 3 30 17 PM" src="https://user-images.githubusercontent.com/14199342/81342133-4ff2aa00-9078-11ea-9442-43bce61bf017.png">
<img width="807" alt="Screen Shot 2020-05-07 at 3 30 10 PM" src="https://user-images.githubusercontent.com/14199342/81342134-508b4080-9078-11ea-9949-81120bade28a.png">
<img width="355" alt="Screen Shot 2020-05-07 at 3 30 05 PM" src="https://user-images.githubusercontent.com/14199342/81342136-5123d700-9078-11ea-8b15-0b8c9f8d6b05.png">

Some odd things happening with the Tabs in the docs
